# # Global variables are applied to all deployments and used as the default value of
# # the deployments if a specific deployment value is missing.
global:
  # # The user who runs the tidb cluster.
  user: "xzx"
  # # group is used to specify the group name the user belong to,if it's not the same as user.
  # group: "tidb"
  # # SSH port of servers in the managed cluster.
  ssh_port: 22
  # # Storage directory for cluster deployment files, startup scripts, and configuration files.
  deploy_dir: "/DATA/disk3/xzx/tiup_deploy/cls"
  # # TiDB Cluster data storage directory
  data_dir: "/DATA/disk3/xzx/tiup_deploy/cls/data"
  # # Supported values: "amd64", "arm64" (default: "amd64")
  arch: "amd64"
  # # Resource Control is used to limit the resource of an instance.
  # # See: https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html
  # # Supports using instance-level `resource_control` to override global `resource_control`.
  # resource_control:
  #   # See: https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html#MemoryLimit=bytes
  #   memory_limit: "2G"
  #   # See: https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html#CPUQuota=
  #   # The percentage specifies how much CPU time the unit shall get at maximum, relative to the total CPU time available on one CPU. Use values > 100% for allotting CPU time on more than one CPU.
  #   # Example: CPUQuota=200% ensures that the executed processes will never get more than two CPU time.
  #   cpu_quota: "200%"
  #   # See: https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html#IOReadBandwidthMax=device%20bytes
  #   io_read_bandwidth_max: "/dev/disk/by-path/pci-0000:00:1f.2-scsi-0:0:0:0 100M"
  #   io_write_bandwidth_max: "/dev/disk/by-path/pci-0000:00:1f.2-scsi-0:0:0:0 100M"

# # Monitored variables are applied to all the machines.
monitored:
  # # The communication port for reporting system information of each node in the TiDB cluster.
  node_exporter_port: 11000
  # # Blackbox_exporter communication port, used for TiDB cluster port monitoring.
  blackbox_exporter_port: 11001
  # # Storage directory for deployment files, startup scripts, and configuration files of monitoring components.
  # deploy_dir: "/tidb-deploy/monitored-9100"
  # # Data storage directory of monitoring components.
  # data_dir: "/tidb-data/monitored-9100"
  # # Log storage directory of the monitoring component.
  # log_dir: "/tidb-deploy/monitored-9100/log"

# # Server configs are used to specify the runtime configuration of TiDB components.
# # All configuration items can be found in TiDB docs:
# # - TiDB: https://pingcap.com/docs/stable/reference/configuration/tidb-server/configuration-file/
# # - TiKV: https://pingcap.com/docs/stable/reference/configuration/tikv-server/configuration-file/
# # - PD: https://pingcap.com/docs/stable/reference/configuration/pd-server/configuration-file/
# # - TiFlash: https://docs.pingcap.com/tidb/stable/tiflash-configuration
# #
# # All configuration items use points to represent the hierarchy, e.g:
# #   readpool.storage.use-unified-pool
# #           ^       ^
# # - example: https://github.com/pingcap/tiup/blob/master/embed/examples/cluster/topology.example.yaml
# # You can overwrite this configuration via the instance-level `config` field.
# server_configs:
  # tidb:
  # tikv:
  # pd:
  # tiflash:
  # tiflash-learner:
  # kvcdc:

# # Server configs are used to specify the configuration of PD Servers.
pd_servers:
  # # The ip address of the PD Server.
  - host: 10.2.12.124
    # # SSH port of the server.
    # ssh_port: 22
    # # PD Server name
    # name: "pd-1"
    # # communication port for TiDB Servers to connect.
    client_port: 2479
    # # communication port among PD Server nodes.
    peer_port: 2480
    # # PD Server deployment file, startup script, configuration file storage directory.
    # deploy_dir: "/tidb-deploy/pd-2379"
    # # PD Server data storage directory.
    # data_dir: "/tidb-data/pd-2379"
    # # PD Server log file storage directory.
    # log_dir: "/tidb-deploy/pd-2379/log"
    # # numa node bindings.
    # numa_node: "0,1"
    # # The following configs are used to overwrite the `server_configs.pd` values.
    # config:
    #   schedule.max-merge-region-size: 20
    #   schedule.max-merge-region-keys: 200000

# # Server configs are used to specify the configuration of TiDB Servers.
tidb_servers:
  # # The ip address of the TiDB Server.
  - host: 10.2.12.124
    # # SSH port of the server.
    # ssh_port: 22
    # # Access the TiDB cluster port.
    port: 8001
    # # TiDB Server status information reporting port.
    status_port: 8002
    # # TiDB Server deployment file, startup script, configuration file storage directory.
    deploy_dir: "/DATA/disk3/xzx/tiup_deploy/cls/tidb-8001"
    # # TiDB Server log file storage directory.
    log_dir: "/DATA/disk3/xzx/tiup_deploy/cls/tidb-8001/log"
    # numa_node: "0" # suggest numa node bindings.

# # Server configs are used to specify the configuration of TiKV Servers.
tikv_servers:
  # # The ip address of the TiKV Server.
  - host: 10.2.12.125
    # # SSH port of the server.
    # ssh_port: 22
    # # TiKV Server communication port.
    port: 8101
    # # Communication port for reporting TiKV Server status.
    status_port: 8204
    # # TiKV Server deployment file, startup script, configuration file storage directory.
    deploy_dir: "/DATA/disk4/xzx/tiup_deploy/cls/tikv-8101"
    # # TiKV Server data storage directory.
    data_dir: "/DATA/disk4/xzx/tiup_deploy/cls/data/tikv-8101"
    # # TiKV Server log file storage directory.
    log_dir: "/DATA/disk4/xzx/tiup_deploy/cls/tikv-8101/log"
    # numa_node: "0"
    # # The following configs are used to overwrite the `server_configs.tikv` values.
    # config:
    #   log.level: warn
  - host: 10.2.12.126
    # ssh_port: 22
    port: 8102
    status_port: 8205
    deploy_dir: "/DATA/disk4/xzx/tiup_deploy/cls/tikv-8102"
    data_dir: "/DATA/disk4/xzx/tiup_deploy/cls/data/tikv-8102"
    log_dir: "/DATA/disk4/xzx/tiup_deploy/cls/tikv-8102/log"
    # numa_node: "1"
    # config:
    #   log.level: warn
  - host: 10.2.12.136
    # ssh_port: 22
    port: 8103
    status_port: 8206
    deploy_dir: "/DATA/disk4/xzx/tiup_deploy/cls/tikv-8103"
    data_dir: "/DATA/disk4/xzx/tiup_deploy/cls/data/tikv-8103"
    log_dir: "/DATA/disk4/xzx/tiup_deploy/cls/tikv-8103/log"
    # numa_node: "0"
    # config:
    #   log.level: warn

# # Server configs are used to specify the configuration of TiFlash Servers.
tiflash_servers:
  # # The ip address of the TiFlash Server.
  - host: 10.2.12.125
    # # SSH port of the server.
    # ssh_port: 22
    # # TiFlash TCP Service port.
    tcp_port: 7003
    http_port: 8223
    # # TiFlash raft service and coprocessor service listening address.
    flash_service_port: 7200
    # # TiFlash Proxy service port.
    flash_proxy_port: 7201
    # # Prometheus pulls TiFlash Proxy metrics port.
    flash_proxy_status_port: 7202
    # # Prometheus pulls the TiFlash metrics port.
    metrics_port: 7203
    # # TiFlash Server deployment file, startup script, configuration file storage directory.
    deploy_dir: /DATA/disk3/xzx/tiup_deploy/cls/tiflash-7003
    ## With cluster version >= v4.0.9 and you want to deploy a multi-disk TiFlash node, it is recommended to
    ## check config.storage.* for details. The data_dir will be ignored if you defined those configurations.
    ## Setting data_dir to a ','-joined string is still supported but deprecated.
    ## Check https://docs.pingcap.com/tidb/stable/tiflash-configuration#multi-disk-deployment for more details.
    # # TiFlash Server data storage directory.
    data_dir: /DATA/disk3/xzx/tiup_deploy/cls/data/tiflash-7003
    # # TiFlash Server log file storage directory.
    log_dir: /DATA/disk3/xzx/tiup_deploy/cls/tiflash-7003/log
  - host: 10.2.12.126
    # # SSH port of the server.
    # ssh_port: 22
    # # TiFlash TCP Service port.
    tcp_port: 7003
    http_port: 8223
    # # TiFlash raft service and coprocessor service listening address.
    flash_service_port: 7200
    # # TiFlash Proxy service port.
    flash_proxy_port: 7201
    # # Prometheus pulls TiFlash Proxy metrics port.
    flash_proxy_status_port: 7202
    # # Prometheus pulls the TiFlash metrics port.
    metrics_port: 7203
    # # TiFlash Server deployment file, startup script, configuration file storage directory.
    deploy_dir: /DATA/disk4/xzx/tiup_deploy/cls/tiflash-7003
    ## With cluster version >= v4.0.9 and you want to deploy a multi-disk TiFlash node, it is recommended to
    ## check config.storage.* for details. The data_dir will be ignored if you defined those configurations.
    ## Setting data_dir to a ','-joined string is still supported but deprecated.
    ## Check https://docs.pingcap.com/tidb/stable/tiflash-configuration#multi-disk-deployment for more details.
    # # TiFlash Server data storage directory.
    data_dir: /DATA/disk4/xzx/tiup_deploy/cls/data/tiflash-7003
    # # TiFlash Server log file storage directory.
    log_dir: /DATA/disk4/xzx/tiup_deploy/cls/tiflash-7003/log
  - host: 10.2.12.136
    # # SSH port of the server.
    # ssh_port: 22
    # # TiFlash TCP Service port.
    tcp_port: 7003
    http_port: 8223
    # # TiFlash raft service and coprocessor service listening address.
    flash_service_port: 7200
    # # TiFlash Proxy service port.
    flash_proxy_port: 7201
    # # Prometheus pulls TiFlash Proxy metrics port.
    flash_proxy_status_port: 7202
    # # Prometheus pulls the TiFlash metrics port.
    metrics_port: 7203
    # # TiFlash Server deployment file, startup script, configuration file storage directory.
    deploy_dir: /DATA/disk4/xzx/tiup_deploy/cls/tiflash-7003
    ## With cluster version >= v4.0.9 and you want to deploy a multi-disk TiFlash node, it is recommended to
    ## check config.storage.* for details. The data_dir will be ignored if you defined those configurations.
    ## Setting data_dir to a ','-joined string is still supported but deprecated.
    ## Check https://docs.pingcap.com/tidb/stable/tiflash-configuration#multi-disk-deployment for more details.
    # # TiFlash Server data storage directory.
    data_dir: /DATA/disk4/xzx/tiup_deploy/cls/data/tiflash-7003
    # # TiFlash Server log file storage directory.
    log_dir: /DATA/disk4/xzx/tiup_deploy/cls/tiflash-7003/log

# # Server configs are used to specify the configuration of Prometheus Server.
monitoring_servers:
  # # The ip address of the Monitoring Server.
  - host: 10.2.12.124
    # # SSH port of the server.
    # ssh_port: 22
    # # Prometheus Service communication port.
    port: 7780
    # # ng-monitoring servive communication port
    ng_port: 13020
    # # Prometheus deployment file, startup script, configuration file storage directory.
    # deploy_dir: "/tidb-deploy/prometheus-8249"
    # # Prometheus data storage directory.
    # data_dir: "/tidb-data/prometheus-8249"
    # # Prometheus log file storage directory.
    # log_dir: "/tidb-deploy/prometheus-8249/log"
    # prometheus rule dir on TiUP machine
    # rule_dir: /home/tidb/prometheus_rule
    # scrape_interval: 15s
    # scrape_timeout: 10s
# # Server configs are used to specify the configuration of Grafana Servers.
grafana_servers:
  # # The ip address of the Grafana Server.
  - host: 10.2.12.124
    # # Grafana Web monitoring service client (browser) access port
    port: 7801
    # # Grafana deployment file, startup script, configuration file storage directory.
    # deploy_dir: /tidb-deploy/grafana-3000
    # grafana dashboard dir on TiUP machine
    # dashboard_dir: /home/tidb/dashboards
    # config:
    #   log.file.level: warning

# # Server configs are used to specify the configuration of Alertmanager Servers.
alertmanager_servers:
  # # The ip address of the Alertmanager Server.
  - host: 10.2.12.124
    # # SSH port of the server.
    # ssh_port: 22
    # Alertmanager web service listen host.
    # listen_host: 0.0.0.0
    # # Alertmanager web service port.
    web_port: 10093
    # # Alertmanager communication port.
    cluster_port: 10094
    # # Alertmanager deployment file, startup script, configuration file storage directory.
    # deploy_dir: "/tidb-deploy/alertmanager-10093"
    # # Alertmanager data storage directory.
    # data_dir: "/tidb-data/alertmanager-10093"
    # # Alertmanager log file storage directory.
    # log_dir: "/tidb-deploy/alertmanager-10093/log"
    # # Alertmanager config file storage directory.
    # config_file: "/tidb-deploy/alertmanager-10093/bin/alertmanager/alertmanager.yml"